; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.6.0
board = esp32-s3-devkitc-1
framework = arduino

; Hardware-specific overrides
board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi

; Partition & Flash Size
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; Build Flags
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; Library Dependencies
lib_deps = 
    https://github.com/T-vK/ESP32-BLE-Keyboard#32c5884

; Monitor Settings
monitor_speed = 115200