; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_esp32_v2]
platform = espressif32 @ 6.6.0
board = adafruit_feather_esp32_v2
framework = arduino

; Partition & Flash Size (Feather V2 hat 8MB Flash)
board_upload.flash_size = 8MB

; Build Flags
build_flags =

; Library Dependencies
lib_deps = 
    https://github.com/T-vK/ESP32-BLE-Keyboard#32c5884

; Monitor Settings
monitor_speed = 115200